mysql.url=jdbc:mysql://192.168.1.169:3306/project_db
mysql.user=friend
mysql.password=80721

quota.default_max_vm=3
quota.default_max_pod=3
quota.default_max_cpu=4
quota.default_max_memory=8Gi

pod.cpu_requests=100m
pod.memory_requests=128Mi
pod.cpu_limit=1
pod.memory_limit=512Mi

sync.period_seconds=30

openstack.auth_url=http://192.168.1.172/identity
openstack.username=demo
openstack.password=Admin123
openstack.domain=Default
openstack.project=demo

k8s.master_url=http://192.168.1.173:8001
k8s.trust_certs=true
k8s.namespace_prefix=user-

prometheus.url=http://192.168.1.169:9090
prometheus.node_exporter_port=9100

pod.logs.max_duration_ms=60000
